version: "2"
services:

  zookeeper-1:
    container_name: zookeeper-1    
    networks: ["vnet"]
    hostname: zookeeper-1.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 1 3 vnet

  zookeeper-2:
    container_name: zookeeper-2    
    networks: ["vnet"]
    hostname: zookeeper-2.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 2 3 vnet

  zookeeper-3:
    container_name: zookeeper-3    
    networks: ["vnet"]
    hostname: zookeeper-3.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 3 3 vnet

  journalnode-1:
    container_name: journalnode-1
    networks: ["vnet"]
    hostname: journalnode-1.vnet
    image: smizy/hadoop-base:2.7.7-alpine
    expose: [8480, 8485]
    environment:
      - SERVICE_8485_NAME=journalnode
      - SERVICE_8480_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      - HADOOP_HEAPSIZE=1000
      
    command: journalnode

  journalnode-2:
    container_name: journalnode-2
    networks: ["vnet"]
    hostname: journalnode-2.vnet
    image: smizy/hadoop-base:2.7.7-alpine
    expose: [8480, 8485]
    environment:
      - SERVICE_8485_NAME=journalnode
      - SERVICE_8480_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      - HADOOP_HEAPSIZE=1000
      
    command: journalnode

  journalnode-3:
    container_name: journalnode-3
    networks: ["vnet"]
    hostname: journalnode-3.vnet
    image: smizy/hadoop-base:2.7.7-alpine
    expose: [8480, 8485]
    environment:
      - SERVICE_8485_NAME=journalnode
      - SERVICE_8480_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      - HADOOP_HEAPSIZE=1000
      
    command: journalnode

  namenode-1:
    container_name: namenode-1
    networks: ["vnet"]
    hostname: namenode-1.vnet
    image: smizy/hadoop-base:2.7.7-alpine 
    expose: ["8020"]
    ports:  ["50070"]
    environment:
      - SERVICE_8020_NAME=namenode
      - SERVICE_50070_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      - HADOOP_HEAPSIZE=1000
      
    entrypoint: entrypoint.sh
    command: namenode-1

  namenode-2:
    container_name: namenode-2
    networks: ["vnet"]
    hostname: namenode-2.vnet
    image: smizy/hadoop-base:2.7.7-alpine 
    expose: ["8020"]
    ports:  ["50070"]
    environment:
      - SERVICE_8020_NAME=namenode
      - SERVICE_50070_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      - HADOOP_HEAPSIZE=1000
      
    entrypoint: entrypoint.sh
    command: namenode-2

  datanode-1:
    container_name: datanode-1
    networks: ["vnet"]
    hostname: datanode-1.vnet
    image: smizy/hadoop-base:2.7.7-alpine
    expose: ["50010", "50020", "50075"]
    environment:
      - SERVICE_50010_NAME=datanode
      - SERVICE_50020_IGNORE=true
      - SERVICE_50075_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      - HADOOP_HEAPSIZE=1000
      
    entrypoint: entrypoint.sh
    command: datanode

  datanode-2:
    container_name: datanode-2
    networks: ["vnet"]
    hostname: datanode-2.vnet
    image: smizy/hadoop-base:2.7.7-alpine
    expose: ["50010", "50020", "50075"]
    environment:
      - SERVICE_50010_NAME=datanode
      - SERVICE_50020_IGNORE=true
      - SERVICE_50075_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      - HADOOP_HEAPSIZE=1000
      
    entrypoint: entrypoint.sh
    command: datanode

  datanode-3:
    container_name: datanode-3
    networks: ["vnet"]
    hostname: datanode-3.vnet
    image: smizy/hadoop-base:2.7.7-alpine
    expose: ["50010", "50020", "50075"]
    environment:
      - SERVICE_50010_NAME=datanode
      - SERVICE_50020_IGNORE=true
      - SERVICE_50075_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      - HADOOP_HEAPSIZE=1000
      
    entrypoint: entrypoint.sh
    command: datanode

  drillbit-1:
    container_name: drillbit-1
    networks: ["vnet"]
    hostname: drillbit-1.vnet
    image: smizy/apache-drill:1.16.0-alpine
    ports: 
      - 8047
    depends_on: ["zookeeper-1"]  
    environment:
      - SERVICE_8047_NAME=drillbit
      - DRILL_HEAP=512M 
      - DRILL_MAX_DIRECT_MEMORY=1G   
      - DRILL_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      

networks:
  vnet:
    external:
      name: vnet 
