version: '2'

services:
  spark-master:
    image: blueskyareahm/spark-base:latest
    hostname: doc-spark-master101.local
    container_name: spark-master101
    ports:
      - 4040:4040
      - 8080:8080
      - 7077:7077
    mem_limit: 1g
    networks:
      spark-nw:
        ipv4_address: 172.30.1.2
    command: /spark/bin/spark-class org.apache.spark.deploy.master.Master --host 0.0.0.0
    extra_hosts:
      - "doc-spark-worker101.local:172.30.1.3"

  spark-worker:
    image: blueskyareahm/spark-base:latest
    hostname: doc-spark-worker101.local
    container_name: spark-worker101
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    mem_limit: 1g
    networks:
      spark-nw:
        ipv4_address: 172.30.1.3
    command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 --host 172.30.1.3
    extra_hosts:
      - "doc-spark-master101.local:172.30.1.2"

networks:
  spark-nw:
    external: true